#pragma once

#define CSV_NO_COLNAMES "CSV NO COLNAMES"
#define CSV_NO_ROWNAMES "CSV NO ROWNAMES"
#define CSV_NO_QUOTE "CSV NO QUOTE"

#define TSV_NO_COLNAMES "TSV NO COLNAMES"
#define TSV_NO_ROWNAMES "TSV NO ROWNAMES"
#define TSV_NO_QUOTE "TSV NO QUOTE"